[package]
name = "bitcoin-aba"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = { version = "0.5.0-rc.1", features = ["json", "uuid"] }
uuid = { version = "0.8.2", features = ["v4"] }

log = "^0.4"
rusqlite = { version = "0.25.3" }